[versions]
kotlin = "1.8.20"
quarkus = "2.16.6.Final"

[libraries]
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus"}
#room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
#android-test-junit4 = { module = "androidx.test.ext:junit:1.1.3", version = "1.1.3" }
#gson = "com.google.code.gson:gson:2.9.0"

[bundles]
#room = ["room-ktx", "room-paging", "room-runtime"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }